name: Python CI (run scripts)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scripts if present
        run: |
          set -e
          [ -f hallo.py ]  && echo "→ hallo.py"  && python hallo.py  || true
          [ -f login.py ]  && echo "→ login.py"  && python login.py  || true
          [ -f logout.py ] && echo "→ logout.py" && python logout.py || true
