name: Python CI (run scripts)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scripts (if they exist)
        run: |
          set -e
          if [ -f hello.py ]; then echo "==> hello.py"; python hello.py; fi
          if [ -f login.py ]; then echo "==> login.py"; python login.py; fi
          if [ -f logout.py ]; then echo "==> logout.py"; python logout.py; fi
